### PR TITLE
Uses strtol instead of atoi so that we can properly handle over/underflow.

### LINKED ISSUE #408: Goto line (Ctrl+I)
```
xed - Version 2.4.2
LinuxMint 19.3 (tricia)
```

**Issue**
Issue is on "goto line function"

**Steps to reproduce**
Open xed on a file (ex: empty file)
Input Ctrl+I
Input a big number of lines like
  1000000000000
  1000000000000000

**Expected behaviour**
The goto line function will go to line number 1

**Other information**

### PR DESCRIPTION
**Pull request by DropsOfSerenity**
This now handles overflow and underflow correctly, by parsing the string
and then clamping the value between INT_MIN and INT_MAX. `atoi` was
giving us garbage values when the buffer overflowed.

Fixes #408

### CODE REVIEW

File: xed/xed-utils.c [hunk 1]
```diff
@@ -61,6 +61,13 @@ xed_gdk_color_to_string (GdkColor color)
     return g_strdup_printf ("#%04x%04x%04x", color.red, color.green, color.blue);
 }
 
+gint
+xed_string_to_clamped_gint (const gchar *text)
+{
+    long int long_line = strtol (text, NULL, 10);
+    return MAX(MIN(long_line, INT_MAX), INT_MIN);
```
Comment (mtwebster) [inline xed/xed-utils.c:68]: Can you just use `CLAMP ()` here?

Comment (DropsOfSerenity) [reply xed/xed-utils.c]: Good point, I didn't realize we had a `CLAMP` macro. Updated and pushed.
